pidx, utils: fix lint warnings
Fix the following linter warnings:

pidx.go:15:5: `pidxFileName` is unused (deadcode)
var pidxFileName = ""
    ^
pidx.go:84:21: Error return value of `pidx.addPdsc` is not checked (errcheck)
        pidx.addPdsc(pdsc)
                    ^
utils.go:74:18: Error return value of `xml.Unmarshal` is not checked (errcheck)
    xml.Unmarshal(contents, targetStruct)
                 ^
makefile:47: recipe for target 'lint' failed

Signed-off-by: Charles Oliveira <charles.oliveira@linaro.org>